### ISSUE TITLE
unhandledRejection Error: Error loading shared library libuuid.so.1

### ISSUE THREAD

**Issue by billmcilhargey** [billmcilhargey/docker-gunbot#2]
user reporting following when loading custom config

unhandledRejection Error: Error loading shared library libuuid.so.1: No such file or directory (needed by /opt/gunbot/node_modules/canvas/build/Release/libpangocairo-1.0.so.0)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1248:18)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/node_modules/canvas/index.js:1:78)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/cs/tables/table.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/cs/overview.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1218:10)
    at Module.load (internal/modules/cjs/loader.js:1047:32)
    at Function.Module._load (internal/modules/cjs/loader.js:935:14)
    at Module.require (internal/modules/cjs/loader.js:1087:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:73:18) Promise [Object] {
  _bitField: 18087936,
  _fulfillmentHandler0: Error: Error loading shared library libuuid.so.1: No such file or directory (needed by /opt/gunbot/node_modules/canvas/build/Release/libpangocairo-1.0.so.0)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:1248:18)
      at Module.load (internal/modules/cjs/loader.js:1047:32)
      at Function.Module._load (internal/modules/cjs/loader.js:935:14)
      at Module.require (internal/modules/cjs/loader.js:1087:19)
      at Module.require (pkg/prelude/bootstrap.js:1225:31)
      at require (internal/modules/cjs/helpers.js:73:18)
      at Object.<anonymous> (/snapshot/enricoranucci/Desktop/Mio/node_modules/canvas/lib/bindings.js:3:18)

**Comment by billmcilhargey** [comment]
still occurring, tracking

**Comment by billmcilhargey** [comment]
should be fixed with latest fixes - pending testing

**Comment by billmcilhargey** [comment]
resolved with the latest fixes
